name: Semantic PR Title

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions: read-all

concurrency:
  group: semantic-pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  validate:
    name: conventional-commit-title
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR title
        uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            docs
            test
            refactor
            chore
            perf
            build
            ci
            style
